apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-list-app
  template:
    metadata:
      labels:
        app: todo-list-app
    spec:
      containers:
        - name: todo-list-app
          image: fahmy1diab/todo-list-app:latest1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-app-service
spec:
  type: LoadBalancer
  selector:
    app: todo-list-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
